"""AI雷达数据集构建器。

用法：
  python -m crawler.crawl                # 联网抓取汇率与数据源，输出 dist/dataset.json + 小程序内置数据
  python -m crawler.crawl --offline      # 只用 data/*.json 种子数据本地合并（不联网）
  python -m crawler.crawl --out path     # 自定义输出路径

输出两份：
  dist/dataset.json            供 CI 提交/上传/推送云数据库
  miniprogram/data/dataset.js  小程序离线兜底数据（module.exports）
"""

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
DIST = ROOT / "dist"
APP_DATA = ROOT / "miniprogram" / "data"

sys.path.insert(0, str(ROOT))
from crawler.fx import get_fx  # noqa: E402
from crawler.sources import run_sources  # noqa: E402
from crawler.validate import validate  # noqa: E402


def _load(name):
    return json.loads((DATA / f"{name}.json").read_text(encoding="utf-8"))


def content_hash(dataset):
    """对「用户可感知的数据内容」做哈希，剔除纯时间戳类易变字段。
    用途：高频轮询下，只有真正的内容变化才写产物/提交/同步云端。
    汇率量化到 2 位小数，避免汇率微小波动触发无意义更新。"""
    slim = json.loads(json.dumps(dataset, ensure_ascii=False))
    slim["generated_at"] = ""
    slim["meta"]["updated_at"] = ""
    slim["meta"].pop("source_notes", None)
    slim["fx"].pop("fetched_at", None)
    if "CNY" in slim["fx"].get("rates", {}):
        slim["fx"]["rates"]["CNY"] = round(float(slim["fx"]["rates"]["CNY"]), 2)
    for m in slim["models"]:
        m.pop("fetched_at", None)
    for a in slim["aggregators"]:
        a.pop("prices_fetched_at", None)
    blob = json.dumps(slim, ensure_ascii=False, sort_keys=True)
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()


def build(offline=False):
    meta = _load("meta")
    providers = _load("providers")["providers"]
    models = _load("models")["models"]
    plans = _load("plans")["plans"]
    free_tiers = _load("free_tiers")["free_tiers"]
    aggregators = _load("aggregators")["aggregators"]
    regions = _load("regional_plans")["regions"]
    regional_plans = _load("regional_plans")["regional_plans"]

    fx = get_fx(offline=offline)
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")

    dataset = {
        "meta": {**meta, "updated_at": now},
        "fx": fx,
        "generated_at": now,
        "providers": providers,
        "models": models,
        "plans": plans,
        "free_tiers": free_tiers,
        "aggregators": aggregators,
        "regions": regions,
        "regional_plans": regional_plans,
    }
    dataset["meta"]["source_notes"] = run_sources(dataset, {"offline": offline, "fx": fx, "now": now})
    return dataset


def write_outputs(dataset):
    DIST.mkdir(exist_ok=True)
    APP_DATA.mkdir(parents=True, exist_ok=True)
    out_json = DIST / "dataset.json"
    out_json.write_text(json.dumps(dataset, ensure_ascii=False, indent=2), encoding="utf-8")
    js = (
        "// AUTO-GENERATED by crawler（data/*.json 的构建产物）—— 请勿手工编辑。\n"
        "// 修改数据请编辑 data/*.json，然后本地构建或推送到 GitHub 由 CI 重建。\n"
        "module.exports = " + json.dumps(dataset, ensure_ascii=False) + ";\n"
    )
    (APP_DATA / "dataset.js").write_text(js, encoding="utf-8")
    return out_json


def main():
    ap = argparse.ArgumentParser(description="构建 AI雷达 数据集")
    ap.add_argument("--out", default=None, help="dataset.json 输出路径（默认 dist/dataset.json）")
    ap.add_argument("--offline", action="store_true", help="不访问网络：使用种子汇率，不运行抓取源")
    ap.add_argument("--force", action="store_true", help="跳过变化检测，强制写产物")
    args = ap.parse_args()

    dataset = build(offline=args.offline)

    errors = validate(dataset)
    if errors:
        for e in errors:
            print("[validate] FAIL:", e, file=sys.stderr)
        sys.exit(1)

    new_hash = content_hash(dataset)
    hash_file = DIST / ".data-hash"
    marker = DIST / ".changed"

    if not args.force and hash_file.exists() and hash_file.read_text(encoding="utf-8").strip() == new_hash:
        marker.unlink(missing_ok=True)
        print("UNCHANGED 数据无实际变化，跳过产物写入（CI 不会提交/同步）")
        if args.out:
            Path(args.out).write_text(json.dumps(dataset, ensure_ascii=False, indent=2), encoding="utf-8")
            print("written:", args.out)
        return

    out = write_outputs(dataset)
    hash_file.write_text(new_hash + "\n", encoding="utf-8")
    marker.write_text("", encoding="utf-8")
    if args.out:
        Path(args.out).write_text(json.dumps(dataset, ensure_ascii=False, indent=2), encoding="utf-8")

    m = dataset["meta"]
    print(
        f"CHANGED version={m['dataset_version']} models={len(dataset['models'])} "
        f"plans={len(dataset['plans'])} free_tiers={len(dataset['free_tiers'])} "
        f"aggregators={len(dataset['aggregators'])} fx_CNY={dataset['fx']['rates']['CNY']}"
    )
    for n in m.get("source_notes", []):
        print("source:", n)
    drift = m.get("drift_report") or []
    for d in drift:
        print(f"drift: {d['model_id']} {d['field']} official=${d['official_usd']} openrouter=${d['openrouter_usd']}")
    print("written:", out)
    print("written:", APP_DATA / "dataset.js")


if __name__ == "__main__":
    main()
