#!/usr/bin/env perl
# 本地离线构建（等价于 python -m crawler.crawl --offline）：
#   perl tools/build_offline.pl
# 读取 data/*.json 种子 → 合并默认汇率 → 校验 → 输出 dist/dataset.json + miniprogram/data/dataset.js
# 适用于本机没有 Python 的场景；正式流程请用 Python 构建或交给 GitHub Actions。

use strict;
use warnings;
use utf8;                  # 脚本内的中文注释按字符处理，避免写文件时双重编码
use JSON::PP;

my $JSON   = JSON::PP->new->canonical;          # 单行输出（dataset.js 用）
my $PRETTY = JSON::PP->new->canonical->pretty;   # 缩进输出（dataset.json 用）
my @BANNED = ('最全', '最低价', '最便宜', '第一名', '最好', '第一品牌');

sub slurp {
    my ($f) = @_;
    open my $fh, '<:encoding(UTF-8)', $f or die "$f: $!";
    local $/;
    my $s = <$fh>;
    close $fh;
    return $s;
}

sub load {
    my ($name) = @_;
    return $JSON->decode(slurp("data/$name.json"));
}

my ($sec, $min, $hour, $mday, $mon, $year) = gmtime();
my $now = sprintf('%04d-%02d-%02dT%02d:%02d:%02d+00:00',
    $year + 1900, $mon + 1, $mday, $hour, $min, $sec);

my $meta       = load('meta');
my $providers  = load('providers')->{providers};
my $models     = load('models')->{models};
my $plans      = load('plans')->{plans};
my $free_tiers = load('free_tiers')->{free_tiers};
my $aggregs    = load('aggregators')->{aggregators};
my $regions    = load('regional_plans')->{regions};
my $regional   = load('regional_plans')->{regional_plans};

$meta->{updated_at}   = $now;
$meta->{source_notes} = ['openrouter: offline 模式跳过', 'deepseek: offline 模式跳过'];

my $ds = {
    meta        => $meta,
    fx          => {
        base       => 'USD',
        rates      => { USD => 1.0, CNY => 7.15, TRY => 42.0, INR => 88.0, NGN => 1500.0, JPY => 150.0, EUR => 0.92 },
        fetched_at => undef,
        source     => 'seed-default（离线默认值，非实时）',
    },
    generated_at  => $now,
    providers     => $providers,
    models        => $models,
    plans         => $plans,
    free_tiers    => $free_tiers,
    aggregators   => $aggregs,
    regions       => $regions,
    regional_plans => $regional,
};

# ---- 校验（与 crawler/validate.py 口径一致的核心项） ----
my @errors;
my %pid = map { $_->{id} => 1 } @$providers;
my %mid;
for my $m (@$models) {
    push @errors, "model $m->{id}: 未知 provider"     unless $pid{ $m->{provider} };
    push @errors, "model $m->{id}: 缺 official_url"   unless $m->{official_url};
    push @errors, "model $m->{id}: 重复 id"           if $mid{ $m->{id} }++;
    if (my $p = $m->{price}) {
        push @errors, "model $m->{id}: 非法币种 $p->{currency}"
            unless $p->{currency} eq 'USD' || $p->{currency} eq 'CNY';
    }
}
for my $pl (@$plans) {
    push @errors, "plan $pl->{id}: 未知 provider" unless $pid{ $pl->{provider} };
}
my $blob = $JSON->encode($ds);
for my $w (@BANNED) {
    push @errors, "内容包含绝对化用语「$w」（广告法风险）" if index($blob, $w) >= 0;
}
if (@errors) {
    print STDERR "[validate] FAIL: $_\n" for @errors;
    exit 1;
}

# ---- 输出 ----
mkdir 'dist' unless -d 'dist';
open my $o, '>:encoding(UTF-8)', 'dist/dataset.json' or die $!;
print {$o} $PRETTY->encode($ds);
close $o;

open my $j, '>:encoding(UTF-8)', 'miniprogram/data/dataset.js' or die $!;
print {$j}
    "// AUTO-GENERATED by crawler (built from data/*.json) -- do not edit by hand.\n",
    "// To change data, edit data/*.json then rebuild locally or let GitHub Actions rebuild it.\n",
    "module.exports = ", $JSON->encode($ds), ";\n";
close $j;

# 本工具总是全量重写，标记为「有变化」，供 crawler/sync.py 手动同步时放行。
# CI 上的 Python 构建有内容哈希检测（dist/.data-hash），无变化时会跳过提交与同步。
open my $mk, '>', 'dist/.changed' or die $!;
close $mk;

printf "OK version=%s models=%d plans=%d free_tiers=%d aggregators=%d\n",
    $meta->{dataset_version}, scalar @$models, scalar @$plans, scalar @$free_tiers, scalar @$aggregs;
print "written: dist/dataset.json\n";
print "written: miniprogram/data/dataset.js\n";
